### ISSUE TITLE
My chip burner version 1.1

### ISSUE THREAD

**Issue by f22b2jesus** [bouletmarc/BMBurner#6]
Downloaded driver and all still wont connect

**Comment by bouletmarc** [comment]
the bmburner v1.1 you got may have become faulty overtime since this unit aren't having any kind of protection for high current protection or for short circuit. If anything have sorted the 5v to the grn lately on the bmburner it is likely to be blown. You can possibly try to replace the ftdi adapter itself but I dont suspect anything to change.

I have added an auto-reset protection fuse on the bmburners of the v2.0 and above to avoid this failure overtime. I would suggest to get your bmburner v1.1 replace by the newest one I got available. Send me a message to my email to discuse about the discount for the replacement burner if you are willing to replace it.

Also please can you report any others issue in the futur over my email that is specified on the back of the bmburner, email : bouletmarc@hotmail.com

Thank you :)
